<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StayEasy.Application\StayEasy.Application.csproj" />
    <ProjectReference Include="..\StayEasy.Infrastructure\StayEasy.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controller\" />
    <Folder Include="MIddleware\" />
  </ItemGroup>

</Project>
